logger:
  level: "INFO"
  logfmt: "%(asctime)s: %(levelname)-8s [%(filename)s:%(lineno)d] %(message)s"
  datefmt: "%Y-%m-%d:%H:%M:%S"

vector_store:
  embedding_model: "all-mpnet-base-v2"
  collection_name: "github_info_collection"

github:
  user: "benntuecon"